# Base simulation config
simulationCycleCount: 30

# Main Island config with Biomes and Surfaces
islandConfig:
  size: 10
  seed: 488567489565351
  noiseCorrelation: 10

  biomeConfig:
    scale: 0.85
    waterPercentage: 0.2
    fieldPercentage: 0.8

  surfaceConfig:
    rockPercentage: 0.2

# Entity config with Animals and Plant configs
  # Density for Plants and Animals
  #    VERY_HIGH  80-100% of maxOnLocation
  #    HIGH       60-80%
  #    MEDIUM     40-60%
  #    LOW        20-40%
  #    VERY_LOW   5-20%
  #    NONE       0%

entitiesConfig:
  animalConfig:
    WOLF:
      weight: 50
      maxOnLocation: 10
      moveSteps: 3
      maxSatiety: 8
      diet:
        edibleAnimals:
          RABBIT: 0.5
        ediblePlants: {}

    RABBIT:
      weight: 2
      maxOnLocation: 20
      moveSteps: 2
      maxSatiety: 0.45
      diet:
        edibleAnimals: {}
        ediblePlants:
          GRASS: 1
          BUSH: 0.8

  plantConfig:
    TREE:
      weight: 1
      maxOnLocation: 20
      allowedBiomes: [ FOREST, FIELD ]
      allowedSurfaces: [ SOIL, ROCK ]
      density:
        FOREST_SOIL: VERY_HIGH
        FOREST_ROCK: HIGH
        FIELD_SOIL: VERY_LOW
        FIELD_ROCK: NONE

    GRASS:
      weight: 0.1
      maxOnLocation: 100
      allowedBiomes: [ FOREST, FIELD ]
      allowedSurfaces: [ SOIL ]
      density:
        FOREST_SOIL: VERY_HIGH
        FIELD_SOIL: HIGH

    BUSH:
      weight: 0.3
      maxOnLocation: 30
      allowedBiomes: [ FOREST, FIELD ]
      allowedSurfaces: [ SOIL, SAND, ROCK ]
      density:
        FOREST_SOIL: HIGH
        FIELD_SOIL: MEDIUM
        FIELD_SAND: MEDIUM
        FIELD_ROCK: LOW

actionConfig:
  # REST
  baseRestMinEnergyRatio: 0.5   # n% from full energy
  sleepRestMinEnergyRatio: 0.1  # n% from full energy
  sleepRestCycleCount: 1
  idleRestMinEnergyRatio: 0.5   # n% from full energy
  idleRestChance: 0.5
  idleRestEnergyBoost: 1.2


  #MOVE
  movementMinEnergyRatio: 0.2   # n% from full energy
  landMoveFindLocationRetries: 5

  #EAT
  eatMinEnergyRatio: 0.05        # n% from full energy

  #REPRODUCE