islandConfig:
  size: 10
  seed: 488567489565351
  noiseCorrelation: 10

  biomeConfig:
    scale: 0.85
    waterPercentage: 0.2
    fieldPercentage: 0.8

  surfaceConfig:
    rockPercentage: 0.2

#
#entityConfig:
#  animalConfig:
#
#    -WOLF:
#      weight: 50
#      maxOnLocation: 30
#      moveSpeed: 3
#      fullnessLimit: 8
#      activityCutoff: 1
#
#    -RABBIT:
#      weight: 2
#      maxOnLocation: 150
#      moveSpeed: 2
#      fullnessLimit: 0.45
#      activityCutoff: 0.1
#
#  plantConfig:
#    -TREE:
#      weight: 1
#      maxOnLocation: 200
#    -GRASS:
#      weight: 0.1
#      maxOnLocation: 200
