islandConfig:
  size: 10
  seed: 488567489565351
  noiseCorrelation: 10

  biomeConfig:
    scale: 0.85
    waterPercentage: 0.2
    fieldPercentage: 0.8

  surfaceConfig:
    rockPercentage: 0.2

entitiesConfig:
  animalConfig:
    WOLF:
      weight: 50
      maxOnLocation: 30
      speed: 3
      maxSatiety: 8

    RABBIT:
      weight: 2
      maxOnLocation: 150
      speed: 2
      maxSatiety: 0.45

#  plantConfig:
#    -TREE:
#      weight: 1
#      maxOnLocation: 200
#    -GRASS:
#      weight: 0.1
#      maxOnLocation: 200
